### ISSUE TITLE
How to make ui-tour to work with angular-translate?

### ISSUE THREAD

**Issue by HenriHeinonen** [angular-ui/ui-tour#12]
How to make ui-tour to work with angular-translate?
For example, this piece of code does not seem to work: `<a ng-click="$ctrl.openCreateSiteModal()" tour-step="home-step90" tour-step-belongs-to="teacherTour" tour-step-title="Collection of sites" tour-step-content="<p>{{'HOME-STEP90-1' | translate}}</p>" tour-step-order = "90" tour-step-placement="right" tour-step-prev-step="home-step80">`

**Comment by ProLoser** [comment]
Not really sure where you got that API from, as none of those fields came from this project. Additionally this project is for the most part inactive. Are you sure you're not confusing this with another project?

**Comment by HenriHeinonen** [comment]
Sorry! I confused this with angular-ui-tour.
